#!/bin/bash

set -x

# Read any custom environment variables.

export PYTHONUNBUFFERED=1
export PYTHONIOENCODING=UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PIP_NO_CACHE_DIR=off

source /opt/spawner/venv/bin/activate

. /opt/spawner/jupyterhub_config.sh

# Start the JupyterHub instance.

exec jupyterhub -f /opt/spawner/jupyterhub_config.py
