apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: learning-portal
  spawner: learning-portal
  class: spawner

resources:
- spawner-service-account.yaml
- spawner-environ-config-map.yaml
- spawner-configs-config-map.yaml
- spawner-cluster-role-binding.yaml
- spawner-deployment.yaml
- spawner-service.yaml
- spawner-ingress.yaml

configMapGenerator:
- name: spawner-environ
  behavior: merge
  literals:
  - CONFIGURATION_TYPE="learning-portal"
  - SERVER_LIMIT="8"
  - RESOURCE_BUDGET="default"
